version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: app
    environment:
      REDIS: redis://redis:6379
    restart: always
    ports:
      - 3001:3000
    networks:
      - network
  redis:
    image: redis
    ports:
      - 6380:6379
    networks:
      - network

networks:
  network:
    driver: bridge
